# Generated by Django 5.1.4 on 2025-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mobile_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
