# Generated by Django 5.1.4 on 2025-02-20 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='investorstock',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.investor'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.investor'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='guider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.guider'),
        ),
    ]
