# Generated by Django 5.1.4 on 2025-02-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0002_alter_guider_user_alter_investor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='investorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('Retirment Planning', 'Retirment Planning'), ('Wealth Building', 'Wealth Building'), ('Tax Saving', 'Tax Saving'), ('Education Fund', 'Education Fund')], default='Wealth Building', max_length=20)),
                ('prefered_date', models.DateField()),
                ('info', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.investor')),
            ],
        ),
    ]
