# Generated by Django 5.1.4 on 2025-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0003_alter_manager_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
