# Generated by Django 5.1.4 on 2025-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0004_alter_manager_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guider',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
