# Generated by Django 5.1.4 on 2025-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0005_alter_guider_isselected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guider',
            name='availibility',
        ),
        migrations.AddField(
            model_name='customuser',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
