# Generated by Django 5.1.4 on 2025-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0007_alter_investorstock_no_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorstock',
            name='price_of_buy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
