# Generated by Django 5.1.4 on 2025-03-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0008_alter_investorstock_price_of_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.investor')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarketanalysis.webinar')),
            ],
        ),
    ]
