# Generated by Django 5.1.4 on 2025-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0009_userwebinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
